### ISSUE TITLE
Il n'est pas possible de voir la couleur du hoodie dans la liste des commandes sur le site admin.

### ISSUE THREAD

**Issue by HandsomeRomanian** [ADEPT-Informatique/adeptinfo.ca#21]
Dans l'interface admin il n'y a rien d’indiquer pour les différentes couleurs il faudrait ajouter un champs qui dit la couleur du hoodie acheté.

**Comment by massicottem** [comment]
Je vais travailler là dessus. Ou sur #23 si @HandsomeRomanian a pas encore commencé.

**Comment by HandsomeRomanian** [comment]
J'avait fait un quick-fix de celui-ci déjà. Le select devrait déjà avoir été modifié il ne reste qu'a changer l'interface.

**Comment by obrassard** [comment]
@massicottem  @HandsomeRomanian donc si je comprends bien, il resterais juste à ajouter une colonne dans le tableau ??

**Comment by obrassard** [comment]
D'après moi tu peux le faire @massicottem
