### ISSUE TITLE
La page produits ne fonctionne plus

### ISSUE THREAD

**Issue by obrassard** [ADEPT-Informatique/adeptinfo.ca#29]
La page produits ne s'affiche pas : https://adeptinfo.ca/produits.php.

Il y a probablement une erreur SQL

**Comment by obrassard** [comment]
<img width="1278" alt="Capture d’écran, le 2019-10-11 à 23 13 10" src="https://user-images.githubusercontent.com/17227551/66693961-b9464200-ec7c-11e9-81fa-53649a392f59.png">

**Comment by HandsomeRomanian** [comment]
- Oups j'ai oublié de faire le changement sur le module de produits lorsque j'ai enlever les fichiers de connexion a la BD qui était dupliquer a plusieurs places dans le projet.

**Comment by HandsomeRomanian** [comment]
#34
