### ISSUE TITLE
Les compteurs de la section "à-propos" n'affichent pas les bons chiffres lorsqu'on scroll dans la page

### ISSUE THREAD

**Issue by obrassard** [ADEPT-Informatique/adeptinfo.ca#4]

**Comment by massicottem** [comment]
Je vais essayer de travailler là dessus! :)

**Comment by obrassard** [comment]
Good merci 🙏🏻

**Comment by obrassard** [comment]
@massicottem Tu me feras penser éventuellement de te parler de la config locale du site sinon tu aura peut-être des problèmes pour que le projet fonctionne correctement

**Comment by massicottem** [comment]
Pull request #28

**Comment by obrassard** [comment]
Résolu dans la PR #28 par @massicottem ! Merci ;)
